### ISSUE TITLE
编译时报错：Could not resolve androidx.databinding:databinding-runtime:3.2.1

### ISSUE THREAD

**Issue by axepudding** [KunMinX/RxJava2-Operators-Sample#1]
解决办法：将buidl.gradle 里的 repositories {
jcenter{}} 修改为： jcenter{ url "http://jcenter.bintray.com/"}

**Comment by KunMinX** [comment]
@axepudding 厉害了。已更新

**Comment by ChenJia-X** [comment]
我是把allprojects中的 repositories {  jcenter{ url "http://jcenter.bintray.com/"} 修改为：jcenter()}才能编译成功，不然一些依赖，比如thereisnospon.codeview:codeview:0.3.1无法下载
