### ISSUE TITLE
为啥不用dagger??

### ISSUE THREAD

**Issue by yacyet** [KunMinX/RxJava2-Operators-Sample#4]
dagger有啥坏处吗?

**Comment by KunMinX** [comment]
@microDD  

你好，dagger 和 eventbus 等框架有个共同的坏处，即缺乏正确理念的约束，这将造成因开发者的滥用或框架本身的设计缺陷导致的：
开发者难以追踪信息源、难以保证数据传递的唯一性和安全性，在项目规模变大的情况下，会指数级地增大出错的概率。

众所周知，在不可预期的错误上花费的时间，往往是惊人的。
具体可参见我在《RxJava 才不是 LiveData 的对手》一文中对现实状况的描述：

https://xiaozhuanlan.com/topic/0168753249
